import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const jost = localFont({
  src: [
    {
      path: '../public/fonts/Jost-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Jost-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/Jost-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/Jost-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-jost',
});

export const metadata = {
  title: {
    default: "VetMeds",
    template: "%s | VetMeds"
  },
  description: "Generated by Omkar M. VeershaivWangi",
};

import NextTopLoader from 'nextjs-toploader';
import { ToastProvider } from "@/components/ToastProvider";
import NetworkStatusHandler from "@/components/NetworkStatusHandler";

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`bg-background text-foreground ${jost.className} ${jost.variable} antialiased`}
      >
        <NextTopLoader 
          color="#1b3a34"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={200}
          shadow="0 0 10px #1b3a34,0 0 5px #1b3a34"
        />
        <NetworkStatusHandler />
        <ToastProvider>
          {children}
        </ToastProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
